services:
  postgres_db:
    image: postgres:15
    container_name: labor_postgres_db
    restart: always
    environment:
      POSTGRES_USER: labor_admin
      POSTGRES_PASSWORD: StrongLocalPassword2026
      POSTGRES_DB: labor_management_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: labor_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@company.com
      PGADMIN_DEFAULT_PASSWORD: StrongLocalPassword2026
    ports:
      - "8085:80" # تم الإبقاء على البورت 8085 للدخول إلى لوحة تحكم قاعدة البيانات pgAdmin
    depends_on:
      - postgres_db

  labor_app:
    build: .
    container_name: labor_app_container
    restart: always
    ports:
      - "3150:3150"
    environment:
      - PORT=3150
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=labor_admin
      - DB_PASSWORD=StrongLocalPassword2026
      - DB_DATABASE=labor_management_db
    depends_on:
      - postgres_db

volumes:
  postgres_data:
