services:
  mariadb_db:
    image: mariadb:10.11
    container_name: labor_mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: StrongLocalRootPassword2026
      MYSQL_USER: labor_admin
      MYSQL_PASSWORD: StrongLocalPassword2026
      MYSQL_DATABASE: labor_management_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: labor_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb_db
      PMA_PORT: 3306
    ports:
      - "8085:80" # تم استخدام البورت 8085 لكي تتجنب بورت 80 المحجوز وبورت 8080 لتفادي أي مشاكل أو تعارضات
    depends_on:
      - mariadb_db

volumes:
  mariadb_data:

